name: QA Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        env:
          GITHUB_ACTION_PATH: ${{ github.action_path }}
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format valgrind bc libcurl4-openssl-dev

      - name: Run style check
        uses: ./.github/actions/style

      - name: Run documentation check
        uses: ./.github/actions/documentation

      - name: Build project
        uses: ./.github/actions/building

      - name: Run tests and coverage
        uses: ./.github/actions/coverage_and_test
